### ISSUE TITLE
Consider an option to highlight lowercase CBM BASIC

### ISSUE THREAD

**Issue by ssokolow** [DNSGeek/vim-cbmbasic#2]
I've got my Caps Lock key remapped, so, when I poke around with CBM BASIC in Vim, I type in lowercase and let the automation fix things.

Given that I've seen other people doing similar things (sometimes as part of `:make` scripting and sometimes as on-save auto-formatting, would you be willing to consider something like a `let` variable that could be set to support highlighting lowercase keywords too?)

**Comment by DNSGeek** [comment]
Done
